### ISSUE TITLE
Add "bug" and "homepage" fields to `package.json`

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/get-github-shortname#1]
### The `bug` and the `homepage` fields. 

Can you describe these two fields, make a PR to `package.json`, and add them? 

More on these, here: https://docs.npmjs.com/files/package.json

Let me know if you want more guidance!

**Comment by danielcber** [comment]
The "bugs" field contains the information which people need to report issues with your module. The field can be populated with a url to your module's issue tracker and/or the email address to which such issues should be reported. Including this information allows for any potential issues with your module to be reported by other developers.

The "homepage" field contains the url to your project's homepage. Including this information in package.json allows for developers to find your project's homepage and all the valuable information it contains.

**Comment by RichardLitt** [comment]
Closed with https://github.com/RichardLitt/open-source-community-maintenance#bugs.
