### ISSUE TITLE
Init package.json

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/get-github-shortname#2]
Look up why having a [`package.json`](https://docs.npmjs.com/files/package.json) is important. 

Can you please make a PR to this repo with that?

**Comment by danielcber** [comment]
package.json is a plain JSON (Java Script Objet Notation) text file which contains the metadata information about your module and is the best way to manage locally installed npm packages. By adding this metadata information to your module you identify it as a unique package, allowing for other developers to to install and update your module using npm. The package.json file also defines which packages your module depends on and allows you to specificy which versions of those packages it should use.

**Comment by RichardLitt** [comment]
Thanks. Added https://github.com/RichardLitt/open-source-community-maintenance#chapter-7-edit-your-package-jason.
