### ISSUE TITLE
Add "authors" field to `package.json`

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/get-github-shortname#3]
I'm being a bit bare-boned here; let me know if you want me to write an example. For now, can you explain what the authors field is, and why it is important?

**Comment by danielcber** [comment]
The "author" field in a package.json file indicates the person who wrote the package, allowing the publisher to share the author's name, email, and url. The "author" field gives credit to the person for writing the package and shares their contact information for people to contact, or learn more about, the author and their projects.

**Comment by RichardLitt** [comment]
Added this to https://github.com/RichardLitt/open-source-community-maintenance#authors. Awesome.
